dist: trusty
sudo: required
language: java

jdk:
  - openjdk8

branches:
 only:
  - master

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: ./gradlew clean buildPlugin
